<a href="https://colab.research.google.com/github/blue9kamrul/ECE_20_04/blob/main/Football_match__pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
matches = pd.read_csv("matches.csv", index_col=0)

In [8]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [10]:
matches.shape

(1389, 27)

In [11]:
matches["team"].value_counts()

team
Manchester United           72
West Ham United             72
Newcastle United            72
Brighton and Hove Albion    72
Southampton                 72
Tottenham Hotspur           71
Manchester City             71
Leeds United                71
Wolverhampton Wanderers     71
Arsenal                     71
Crystal Palace              71
Burnley                     71
Chelsea                     70
Aston Villa                 70
Leicester City              70
Everton                     70
West Bromwich Albion        38
Fulham                      38
Liverpool                   38
Sheffield United            38
Brentford                   34
Norwich City                33
Watford                     33
Name: count, dtype: int64

In [13]:
matches[matches["team"] == "Liverpool"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,Leeds United,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,Chelsea,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,Arsenal,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,Aston Villa,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,Everton,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,West Ham,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,Manchester City,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,Leicester City,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,Brighton,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,Wolves,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,Fulham,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,Tottenham,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,Crystal Palace,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,West Brom,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,Newcastle Utd,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,Southampton,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,Manchester Utd,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,Burnley,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,Tottenham,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,West Ham,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,Brighton,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,Manchester City,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,Leicester City,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,Everton,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,Chelsea,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,Fulham,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,Wolves,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,Arsenal,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,Leeds United,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,Newcastle Utd,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,Southampton,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,Manchester Utd,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,West Brom,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [14]:
matches["round"].value_counts()

round
Matchweek 1     39
Matchweek 2     39
Matchweek 3     39
Matchweek 4     39
Matchweek 5     39
Matchweek 6     39
Matchweek 7     39
Matchweek 8     39
Matchweek 9     39
Matchweek 10    39
Matchweek 11    39
Matchweek 12    39
Matchweek 13    39
Matchweek 14    39
Matchweek 15    39
Matchweek 16    39
Matchweek 17    39
Matchweek 19    39
Matchweek 20    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 34    39
Matchweek 29    39
Matchweek 31    39
Matchweek 26    39
Matchweek 28    39
Matchweek 32    39
Matchweek 18    37
Matchweek 21    37
Matchweek 22    37
Matchweek 27    37
Matchweek 30    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: count, dtype: int64

In [15]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [16]:
#ML cant work with object or float-int 64 data. so we need a way to clean them for ml purpose

In [17]:
matches["date"] = pd.to_datetime(matches["date"])

In [18]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,...,Match Report,NaN,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United

In [19]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [20]:
#creating predictors
#home or away turning into num
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [23]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [24]:
matches["hour"] = matches["time"].str.replace(":.+","",regex = True).astype("int")

In [26]:
matches["opponent"].value_counts()

opponent
Southampton        71
Liverpool          71
Newcastle Utd      71
Manchester Utd     70
West Ham           70
Brighton           70
Tottenham          70
Wolves             70
Manchester City    69
Crystal Palace     69
Arsenal            69
Leeds United       69
Aston Villa        69
Burnley            69
Leicester City     68
Everton            68
Chelsea            68
West Brom          38
Fulham             38
Sheffield Utd      38
Brentford          32
Norwich City       31
Watford            31
Name: count, dtype: int64

In [27]:
matches['day_code'] = matches["date"].dt.dayofweek

In [29]:
#train ML model now
#setting up target
matches["target"] = (matches["result"] == "W").astype("int")

In [31]:
from sklearn.ensemble import RandomForestClassifier
#rfc is good for picking non linear data in the dataset

In [32]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [33]:
train = matches[matches["date"] < '2022-01-01']

In [35]:
test = matches[matches["date"] > '2022-01-01']

In [36]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [37]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [38]:
preds = rf.predict(test[predictors])

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
acc = accuracy_score(test["target"], preds)

In [41]:
acc

0.6123188405797102

In [42]:
combined = pd.DataFrame(dict(actual=test["target"], predictions=preds))

In [44]:
pd.crosstab(index=combined["actual"], columns=combined["predictions"])
#here we were trying to predict how much accurately we can pred win so our model did not perform well enough. so need to revise the accuracy

predictions    0   1
actual
0            141  31
1             76  28

In [45]:
from sklearn.metrics import precision_score

In [46]:
precision_score(test["target"], preds)

0.4745762711864407